# Full set of configurations
# you can also set the subscriber_queue, publisher_queue, and lazy parameters, which are optional.

# atlas robot
- ros_topic_name: "atlas/velodyne_points"
  gz_topic_name: "atlas/laser_scan/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "ignition.msgs.PointCloudPacked"
  direction: GZ_TO_ROS

- ros_topic_name: "atlas/rgbd_points"
  gz_topic_name: "atlas/rgbd_camera/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "ignition.msgs.PointCloudPacked"
  direction: GZ_TO_ROS

- ros_topic_name: "atlas/rgbd_camera_info"
  gz_topic_name: "atlas/rgbd_camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "ignition.msgs.CameraInfo"
  direction: GZ_TO_ROS

- ros_topic_name: "atlas/rgbd_camera_image"
  gz_topic_name: "atlas/rgbd_camera/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "atlas/rgbd_camera_depth_image"
  gz_topic_name: "atlas/rgbd_camera/depth_image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "atlas/imu/data"
  gz_topic_name: "atlas/imu/data"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "ignition.msgs.IMU"
  direction: GZ_TO_ROS

- ros_topic_name: "atlas/odom_ground_truth"
  gz_topic_name: "atlas/odom_ground_truth"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "ignition.msgs.Odometry"
  direction: GZ_TO_ROS

- ros_topic_name: "atlas/pose"
  gz_topic_name: "model/atlas/pose"
  ros_type_name: "geometry_msgs/msg/PoseArray"
  gz_type_name: "ignition.msgs.Pose_V"
  direction: GZ_TO_ROS

- ros_topic_name: "atlas/cmd_vel"
  gz_topic_name: "atlas/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "ignition.msgs.Twist"
  direction: ROS_TO_GZ

# bestla robot
- ros_topic_name: "bestla/velodyne_points"
  gz_topic_name: "bestla/laser_scan/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "ignition.msgs.PointCloudPacked"
  direction: GZ_TO_ROS

- ros_topic_name: "bestla/rgbd_points"
  gz_topic_name: "bestla/rgbd_camera/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "ignition.msgs.PointCloudPacked"
  direction: GZ_TO_ROS

- ros_topic_name: "bestla/rgbd_camera_info"
  gz_topic_name: "bestla/rgbd_camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "ignition.msgs.CameraInfo"
  direction: GZ_TO_ROS

- ros_topic_name: "bestla/rgbd_camera_image"
  gz_topic_name: "bestla/rgbd_camera/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "bestla/rgbd_camera_depth_image"
  gz_topic_name: "bestla/rgbd_camera/depth_image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "bestla/imu/data"
  gz_topic_name: "bestla/imu/data"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "ignition.msgs.IMU"
  direction: GZ_TO_ROS

- ros_topic_name: "bestla/odom_ground_truth"
  gz_topic_name: "bestla/odom_ground_truth"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "ignition.msgs.Odometry"
  direction: GZ_TO_ROS

- ros_topic_name: "bestla/pose"
  gz_topic_name: "model/bestla/pose"
  ros_type_name: "geometry_msgs/msg/PoseArray"
  gz_type_name: "ignition.msgs.Pose_V"
  direction: GZ_TO_ROS

- ros_topic_name: "bestla/cmd_vel"
  gz_topic_name: "bestla/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "ignition.msgs.Twist"
  direction: ROS_TO_GZ

# rama robot
- ros_topic_name: "rama/rgbd_points"
  gz_topic_name: "rama/rgbd_camera/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "ignition.msgs.PointCloudPacked"
  direction: GZ_TO_ROS

- ros_topic_name: "rama/rgbd_camera_info"
  gz_topic_name: "rama/rgbd_camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "ignition.msgs.CameraInfo"
  direction: GZ_TO_ROS

- ros_topic_name: "rama/rgbd_camera_image"
  gz_topic_name: "rama/rgbd_camera/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "rama/rgbd_camera_depth_image"
  gz_topic_name: "rama/rgbd_camera/depth_image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "rama/imu/data"
  gz_topic_name: "rama/imu/data"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "ignition.msgs.IMU"
  direction: GZ_TO_ROS

- ros_topic_name: "rama/odom_ground_truth"
  gz_topic_name: "rama/odom_ground_truth"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "ignition.msgs.Odometry"
  direction: GZ_TO_ROS

- ros_topic_name: "rama/pose"
  gz_topic_name: "model/rama/pose"
  ros_type_name: "geometry_msgs/msg/PoseArray"
  gz_type_name: "ignition.msgs.Pose_V"
  direction: GZ_TO_ROS

- ros_topic_name: "rama/cmd_vel"
  gz_topic_name: "rama/uav/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "ignition.msgs.Twist"
  direction: ROS_TO_GZ

# ravana robot
- ros_topic_name: "ravana/rgbd_points"
  gz_topic_name: "ravana/rgbd_camera/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "ignition.msgs.PointCloudPacked"
  direction: GZ_TO_ROS

- ros_topic_name: "ravana/rgbd_camera_info"
  gz_topic_name: "ravana/rgbd_camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "ignition.msgs.CameraInfo"
  direction: GZ_TO_ROS

- ros_topic_name: "ravana/rgbd_camera_image"
  gz_topic_name: "ravana/rgbd_camera/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "ravana/rgbd_camera_depth_image"
  gz_topic_name: "ravana/rgbd_camera/depth_image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "ravana/imu/data"
  gz_topic_name: "ravana/imu/data"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "ignition.msgs.IMU"
  direction: GZ_TO_ROS

- ros_topic_name: "ravana/odom_ground_truth"
  gz_topic_name: "ravana/odom_ground_truth"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "ignition.msgs.Odometry"
  direction: GZ_TO_ROS

- ros_topic_name: "ravana/pose"
  gz_topic_name: "model/ravana/pose"
  ros_type_name: "geometry_msgs/msg/PoseArray"
  gz_type_name: "ignition.msgs.Pose_V"
  direction: GZ_TO_ROS

- ros_topic_name: "ravana/cmd_vel"
  gz_topic_name: "ravana/uav/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "ignition.msgs.Twist"
  direction: ROS_TO_GZ

- ros_topic_name: "clock"
  gz_topic_name: "clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "ignition.msgs.Clock"
  direction: GZ_TO_ROS